//
//  Upscaler engine (injected into xbox.com/play pages by the app).
//  Implements AMD FidelityFX Super Resolution 1 (EASU + RCAS) as a WebGL2
//  post-process over the stream's <video> element, rendering at native
//  devicePixelRatio for maximum sharpness.
//
//  Mode is controlled via localStorage "XCG.Upscaler" ("off" | "fsr1") and
//  window messages { type: "xcg-upscaler", mode: "..." }.
//
(function () {
  "use strict";

  var FFX_DEFINES = `#define A_STATIC
#define AP1 bool
#define FSR_RCAS_LIMIT 0.25
#define AF1 float
#define AF2 vec2
#define AF3 vec3
#define AF4 vec4
#define AU1 uint
#define AU2 uvec2
#define AU4 uvec4
#define ASU2 ivec2
#define AF1_(x) float(x)
#define AF2_(x) vec2(x)
#define AF3_(x) vec3(x)
#define AF4_(x) vec4(x)
#define AU1_(x) uint(x)
#define AU2_(x) uvec2(x)
#define AF2_AU2(x) vec2(x)
#define ASatF1(a) clamp((a), 0.0, 1.0)
#define AMin3F1(a,b,c) min(a, min(b, c))
#define AMax3F1(a,b,c) max(a, max(b, c))
#define AMin3F3(a,b,c) min(a, min(b, c))
#define AMax3F3(a,b,c) max(a, max(b, c))
#define ARcpF1(a) (1.0 / (a))
#define APrxLoRcpF1(a) (1.0 / (a))
#define APrxMedRcpF1(a) (1.0 / (a))
#define APrxLoRsqF1(a) inversesqrt(a)
#define AF1_AU1(x) uintBitsToFloat(x)
#define AU1_AF1(x) floatBitsToUint(x)`;
  var FFX_EASU_BLOCK = ` // Input callback prototypes, need to be implemented by calling shader
 AF4 FsrEasuRF(AF2 p);
 AF4 FsrEasuGF(AF2 p);
 AF4 FsrEasuBF(AF2 p);
//------------------------------------------------------------------------------------------------------------------------------
 // Filtering for a given tap for the scalar.
 void FsrEasuTapF(
 inout AF3 aC, // Accumulated color, with negative lobe.
 inout AF1 aW, // Accumulated weight.
 AF2 off, // Pixel offset from resolve position to tap.
 AF2 dir, // Gradient direction.
 AF2 len, // Length.
 AF1 lob, // Negative lobe strength.
 AF1 clp, // Clipping point.
 AF3 c){ // Tap color.
  // Rotate offset by direction.
  AF2 v;
  v.x=(off.x*( dir.x))+(off.y*dir.y);
  v.y=(off.x*(-dir.y))+(off.y*dir.x);
  // Anisotropy.
  v*=len;
  // Compute distance^2.
  AF1 d2=v.x*v.x+v.y*v.y;
  // Limit to the window as at corner, 2 taps can easily be outside.
  d2=min(d2,clp);
  // Approximation of lancos2 without sin() or rcp(), or sqrt() to get x.
  //  (25/16 * (2/5 * x^2 - 1)^2 - (25/16 - 1)) * (1/4 * x^2 - 1)^2
  //  |_______________________________________|   |_______________|
  //                   base                             window
  // The general form of the 'base' is,
  //  (a*(b*x^2-1)^2-(a-1))
  // Where 'a=1/(2*b-b^2)' and 'b' moves around the negative lobe.
  AF1 wB=AF1_(2.0/5.0)*d2+AF1_(-1.0);
  AF1 wA=lob*d2+AF1_(-1.0);
  wB*=wB;
  wA*=wA;
  wB=AF1_(25.0/16.0)*wB+AF1_(-(25.0/16.0-1.0));
  AF1 w=wB*wA;
  // Do weighted average.
  aC+=c*w;aW+=w;}
//------------------------------------------------------------------------------------------------------------------------------
 // Accumulate direction and length.
 void FsrEasuSetF(
 inout AF2 dir,
 inout AF1 len,
 AF2 pp,
 AP1 biS,AP1 biT,AP1 biU,AP1 biV,
 AF1 lA,AF1 lB,AF1 lC,AF1 lD,AF1 lE){
  // Compute bilinear weight, branches factor out as predicates are compiler time immediates.
  //  s t
  //  u v
  AF1 w = AF1_(0.0);
  if(biS)w=(AF1_(1.0)-pp.x)*(AF1_(1.0)-pp.y);
  if(biT)w=           pp.x *(AF1_(1.0)-pp.y);
  if(biU)w=(AF1_(1.0)-pp.x)*           pp.y ;
  if(biV)w=           pp.x *           pp.y ;
  // Direction is the '+' diff.
  //    a
  //  b c d
  //    e
  // Then takes magnitude from abs average of both sides of 'c'.
  // Length converts gradient reversal to 0, smoothly to non-reversal at 1, shaped, then adding horz and vert terms.
  AF1 dc=lD-lC;
  AF1 cb=lC-lB;
  AF1 lenX=max(abs(dc),abs(cb));
  lenX=APrxLoRcpF1(lenX);
  AF1 dirX=lD-lB;
  dir.x+=dirX*w;
  lenX=ASatF1(abs(dirX)*lenX);
  lenX*=lenX;
  len+=lenX*w;
  // Repeat for the y axis.
  AF1 ec=lE-lC;
  AF1 ca=lC-lA;
  AF1 lenY=max(abs(ec),abs(ca));
  lenY=APrxLoRcpF1(lenY);
  AF1 dirY=lE-lA;
  dir.y+=dirY*w;
  lenY=ASatF1(abs(dirY)*lenY);
  lenY*=lenY;
  len+=lenY*w;}
//------------------------------------------------------------------------------------------------------------------------------
 void FsrEasuF(
 out AF3 pix,
 AU2 ip, // Integer pixel position in output.
 AU4 con0, // Constants generated by FsrEasuCon().
 AU4 con1,
 AU4 con2,
 AU4 con3){
//------------------------------------------------------------------------------------------------------------------------------
  // Get position of 'f'.
  AF2 pp=AF2(ip)*AF2_AU2(con0.xy)+AF2_AU2(con0.zw);
  AF2 fp=floor(pp);
  pp-=fp;
//------------------------------------------------------------------------------------------------------------------------------
  // 12-tap kernel.
  //    b c
  //  e f g h
  //  i j k l
  //    n o
  // Gather 4 ordering.
  //  a b
  //  r g
  // For packed FP16, need either {rg} or {ab} so using the following setup for gather in all versions,
  //    a b    <- unused (z)
  //    r g
  //  a b a b
  //  r g r g
  //    a b
  //    r g    <- unused (z)
  // Allowing dead-code removal to remove the 'z's.
  AF2 p0=fp*AF2_AU2(con1.xy)+AF2_AU2(con1.zw);
  // These are from p0 to avoid pulling two constants on pre-Navi hardware.
  AF2 p1=p0+AF2_AU2(con2.xy);
  AF2 p2=p0+AF2_AU2(con2.zw);
  AF2 p3=p0+AF2_AU2(con3.xy);
  AF4 bczzR=FsrEasuRF(p0);
  AF4 bczzG=FsrEasuGF(p0);
  AF4 bczzB=FsrEasuBF(p0);
  AF4 ijfeR=FsrEasuRF(p1);
  AF4 ijfeG=FsrEasuGF(p1);
  AF4 ijfeB=FsrEasuBF(p1);
  AF4 klhgR=FsrEasuRF(p2);
  AF4 klhgG=FsrEasuGF(p2);
  AF4 klhgB=FsrEasuBF(p2);
  AF4 zzonR=FsrEasuRF(p3);
  AF4 zzonG=FsrEasuGF(p3);
  AF4 zzonB=FsrEasuBF(p3);
//------------------------------------------------------------------------------------------------------------------------------
  // Simplest multi-channel approximate luma possible (luma times 2, in 2 FMA/MAD).
  AF4 bczzL=bczzB*AF4_(0.5)+(bczzR*AF4_(0.5)+bczzG);
  AF4 ijfeL=ijfeB*AF4_(0.5)+(ijfeR*AF4_(0.5)+ijfeG);
  AF4 klhgL=klhgB*AF4_(0.5)+(klhgR*AF4_(0.5)+klhgG);
  AF4 zzonL=zzonB*AF4_(0.5)+(zzonR*AF4_(0.5)+zzonG);
  // Rename.
  AF1 bL=bczzL.x;
  AF1 cL=bczzL.y;
  AF1 iL=ijfeL.x;
  AF1 jL=ijfeL.y;
  AF1 fL=ijfeL.z;
  AF1 eL=ijfeL.w;
  AF1 kL=klhgL.x;
  AF1 lL=klhgL.y;
  AF1 hL=klhgL.z;
  AF1 gL=klhgL.w;
  AF1 oL=zzonL.z;
  AF1 nL=zzonL.w;
  // Accumulate for bilinear interpolation.
  AF2 dir=AF2_(0.0);
  AF1 len=AF1_(0.0);
  FsrEasuSetF(dir,len,pp,true, false,false,false,bL,eL,fL,gL,jL);
  FsrEasuSetF(dir,len,pp,false,true ,false,false,cL,fL,gL,hL,kL);
  FsrEasuSetF(dir,len,pp,false,false,true ,false,fL,iL,jL,kL,nL);
  FsrEasuSetF(dir,len,pp,false,false,false,true ,gL,jL,kL,lL,oL);
//------------------------------------------------------------------------------------------------------------------------------
  // Normalize with approximation, and cleanup close to zero.
  AF2 dir2=dir*dir;
  AF1 dirR=dir2.x+dir2.y;
  AP1 zro=dirR<AF1_(1.0/32768.0);
  dirR=APrxLoRsqF1(dirR);
  dirR=zro?AF1_(1.0):dirR;
  dir.x=zro?AF1_(1.0):dir.x;
  dir*=AF2_(dirR);
  // Transform from {0 to 2} to {0 to 1} range, and shape with square.
  len=len*AF1_(0.5);
  len*=len;
  // Stretch kernel {1.0 vert|horz, to sqrt(2.0) on diagonal}.
  AF1 stretch=(dir.x*dir.x+dir.y*dir.y)*APrxLoRcpF1(max(abs(dir.x),abs(dir.y)));
  // Anisotropic length after rotation,
  //  x := 1.0 lerp to 'stretch' on edges
  //  y := 1.0 lerp to 2x on edges
  AF2 len2=AF2(AF1_(1.0)+(stretch-AF1_(1.0))*len,AF1_(1.0)+AF1_(-0.5)*len);
  // Based on the amount of 'edge',
  // the window shifts from +/-{sqrt(2.0) to slightly beyond 2.0}.
  AF1 lob=AF1_(0.5)+AF1_((1.0/4.0-0.04)-0.5)*len;
  // Set distance^2 clipping point to the end of the adjustable window.
  AF1 clp=APrxLoRcpF1(lob);
//------------------------------------------------------------------------------------------------------------------------------
  // Accumulation mixed with min/max of 4 nearest.
  //    b c
  //  e f g h
  //  i j k l
  //    n o
  AF3 min4=min(AMin3F3(AF3(ijfeR.z,ijfeG.z,ijfeB.z),AF3(klhgR.w,klhgG.w,klhgB.w),AF3(ijfeR.y,ijfeG.y,ijfeB.y)),
               AF3(klhgR.x,klhgG.x,klhgB.x));
  AF3 max4=max(AMax3F3(AF3(ijfeR.z,ijfeG.z,ijfeB.z),AF3(klhgR.w,klhgG.w,klhgB.w),AF3(ijfeR.y,ijfeG.y,ijfeB.y)),
               AF3(klhgR.x,klhgG.x,klhgB.x));
  // Accumulation.
  AF3 aC=AF3_(0.0);
  AF1 aW=AF1_(0.0);
  FsrEasuTapF(aC,aW,AF2( 0.0,-1.0)-pp,dir,len2,lob,clp,AF3(bczzR.x,bczzG.x,bczzB.x)); // b
  FsrEasuTapF(aC,aW,AF2( 1.0,-1.0)-pp,dir,len2,lob,clp,AF3(bczzR.y,bczzG.y,bczzB.y)); // c
  FsrEasuTapF(aC,aW,AF2(-1.0, 1.0)-pp,dir,len2,lob,clp,AF3(ijfeR.x,ijfeG.x,ijfeB.x)); // i
  FsrEasuTapF(aC,aW,AF2( 0.0, 1.0)-pp,dir,len2,lob,clp,AF3(ijfeR.y,ijfeG.y,ijfeB.y)); // j
  FsrEasuTapF(aC,aW,AF2( 0.0, 0.0)-pp,dir,len2,lob,clp,AF3(ijfeR.z,ijfeG.z,ijfeB.z)); // f
  FsrEasuTapF(aC,aW,AF2(-1.0, 0.0)-pp,dir,len2,lob,clp,AF3(ijfeR.w,ijfeG.w,ijfeB.w)); // e
  FsrEasuTapF(aC,aW,AF2( 1.0, 1.0)-pp,dir,len2,lob,clp,AF3(klhgR.x,klhgG.x,klhgB.x)); // k
  FsrEasuTapF(aC,aW,AF2( 2.0, 1.0)-pp,dir,len2,lob,clp,AF3(klhgR.y,klhgG.y,klhgB.y)); // l
  FsrEasuTapF(aC,aW,AF2( 2.0, 0.0)-pp,dir,len2,lob,clp,AF3(klhgR.z,klhgG.z,klhgB.z)); // h
  FsrEasuTapF(aC,aW,AF2( 1.0, 0.0)-pp,dir,len2,lob,clp,AF3(klhgR.w,klhgG.w,klhgB.w)); // g
  FsrEasuTapF(aC,aW,AF2( 1.0, 2.0)-pp,dir,len2,lob,clp,AF3(zzonR.z,zzonG.z,zzonB.z)); // o
  FsrEasuTapF(aC,aW,AF2( 0.0, 2.0)-pp,dir,len2,lob,clp,AF3(zzonR.w,zzonG.w,zzonB.w)); // n
//------------------------------------------------------------------------------------------------------------------------------
  // Normalize and dering.
  pix=min(max4,max(min4,aC*AF3_(ARcpF1(aW))));}`;
  var FFX_RCAS_BLOCK = ` // Input callback prototypes that need to be implemented by calling shader
 AF4 FsrRcasLoadF(ASU2 p);
 void FsrRcasInputF(inout AF1 r,inout AF1 g,inout AF1 b);
//------------------------------------------------------------------------------------------------------------------------------
 void FsrRcasF(
 out AF1 pixR, // Output values, non-vector so port between RcasFilter() and RcasFilterH() is easy.
 out AF1 pixG,
 out AF1 pixB,
 #ifdef FSR_RCAS_PASSTHROUGH_ALPHA
  out AF1 pixA,
 #endif
 AU2 ip, // Integer pixel position in output.
 AU4 con){ // Constant generated by RcasSetup().
  // Algorithm uses minimal 3x3 pixel neighborhood.
  //    b 
  //  d e f
  //    h
  ASU2 sp=ASU2(ip);
  AF3 b=FsrRcasLoadF(sp+ASU2( 0,-1)).rgb;
  AF3 d=FsrRcasLoadF(sp+ASU2(-1, 0)).rgb;
  #ifdef FSR_RCAS_PASSTHROUGH_ALPHA
   AF4 ee=FsrRcasLoadF(sp);
   AF3 e=ee.rgb;pixA=ee.a;
  #else
   AF3 e=FsrRcasLoadF(sp).rgb;
  #endif
  AF3 f=FsrRcasLoadF(sp+ASU2( 1, 0)).rgb;
  AF3 h=FsrRcasLoadF(sp+ASU2( 0, 1)).rgb;
  // Rename (32-bit) or regroup (16-bit).
  AF1 bR=b.r;
  AF1 bG=b.g;
  AF1 bB=b.b;
  AF1 dR=d.r;
  AF1 dG=d.g;
  AF1 dB=d.b;
  AF1 eR=e.r;
  AF1 eG=e.g;
  AF1 eB=e.b;
  AF1 fR=f.r;
  AF1 fG=f.g;
  AF1 fB=f.b;
  AF1 hR=h.r;
  AF1 hG=h.g;
  AF1 hB=h.b;
  // Run optional input transform.
  FsrRcasInputF(bR,bG,bB);
  FsrRcasInputF(dR,dG,dB);
  FsrRcasInputF(eR,eG,eB);
  FsrRcasInputF(fR,fG,fB);
  FsrRcasInputF(hR,hG,hB);
  // Luma times 2.
  AF1 bL=bB*AF1_(0.5)+(bR*AF1_(0.5)+bG);
  AF1 dL=dB*AF1_(0.5)+(dR*AF1_(0.5)+dG);
  AF1 eL=eB*AF1_(0.5)+(eR*AF1_(0.5)+eG);
  AF1 fL=fB*AF1_(0.5)+(fR*AF1_(0.5)+fG);
  AF1 hL=hB*AF1_(0.5)+(hR*AF1_(0.5)+hG);
  // Noise detection.
  AF1 nz=AF1_(0.25)*bL+AF1_(0.25)*dL+AF1_(0.25)*fL+AF1_(0.25)*hL-eL;
  nz=ASatF1(abs(nz)*APrxMedRcpF1(AMax3F1(AMax3F1(bL,dL,eL),fL,hL)-AMin3F1(AMin3F1(bL,dL,eL),fL,hL)));
  nz=AF1_(-0.5)*nz+AF1_(1.0);
  // Min and max of ring.
  AF1 mn4R=min(AMin3F1(bR,dR,fR),hR);
  AF1 mn4G=min(AMin3F1(bG,dG,fG),hG);
  AF1 mn4B=min(AMin3F1(bB,dB,fB),hB);
  AF1 mx4R=max(AMax3F1(bR,dR,fR),hR);
  AF1 mx4G=max(AMax3F1(bG,dG,fG),hG);
  AF1 mx4B=max(AMax3F1(bB,dB,fB),hB);
  // Immediate constants for peak range.
  AF2 peakC=AF2(1.0,-1.0*4.0);
  // Limiters, these need to be high precision RCPs.
  AF1 hitMinR=min(mn4R,eR)*ARcpF1(AF1_(4.0)*mx4R);
  AF1 hitMinG=min(mn4G,eG)*ARcpF1(AF1_(4.0)*mx4G);
  AF1 hitMinB=min(mn4B,eB)*ARcpF1(AF1_(4.0)*mx4B);
  AF1 hitMaxR=(peakC.x-max(mx4R,eR))*ARcpF1(AF1_(4.0)*mn4R+peakC.y);
  AF1 hitMaxG=(peakC.x-max(mx4G,eG))*ARcpF1(AF1_(4.0)*mn4G+peakC.y);
  AF1 hitMaxB=(peakC.x-max(mx4B,eB))*ARcpF1(AF1_(4.0)*mn4B+peakC.y);
  AF1 lobeR=max(-hitMinR,hitMaxR);
  AF1 lobeG=max(-hitMinG,hitMaxG);
  AF1 lobeB=max(-hitMinB,hitMaxB);
  AF1 lobe=max(AF1_(-FSR_RCAS_LIMIT),min(AMax3F1(lobeR,lobeG,lobeB),AF1_(0.0)))*AF1_AU1(con.x);
  // Apply noise removal.
  #ifdef FSR_RCAS_DENOISE
   lobe*=nz;
  #endif
  // Resolve, which needs the medium precision rcp approximation to avoid visible tonality changes.
  AF1 rcpL=APrxMedRcpF1(AF1_(4.0)*lobe+AF1_(1.0));
  pixR=(lobe*bR+lobe*dR+lobe*hR+lobe*fR+eR)*rcpL;
  pixG=(lobe*bG+lobe*dG+lobe*hG+lobe*fG+eG)*rcpL;
  pixB=(lobe*bB+lobe*dB+lobe*hB+lobe*fB+eB)*rcpL;
  return;} `;

  var mode = "off";
  try { mode = localStorage.getItem("XCG.Upscaler") || "off"; } catch (e) {}

  var canvas = null;
  var gl = null;
  var video = null;
  var rafId = 0;
  var programs = {};
  var fbo = null;
  var fboTex = null;
  var fboSize = [0, 0];
  var detachObserver = null;
  var uniformEasu = null;
  var uniformRcas = null;

  var VERT = [
    "#version 300 es",
    "in vec2 aPos;",
    "out vec2 vUV;",
    "void main(){ vUV = aPos * 0.5 + 0.5; gl_Position = vec4(aPos, 0.0, 1.0); }"
  ].join("\n");

  function easuFrag() {
    return [
      "#version 300 es",
      "precision highp float;",
    "out vec4 frag;",
      "uniform sampler2D uTex;",
      "uniform vec2 uTexel;",
      "uniform uvec4 uCon0;",
      "uniform uvec4 uCon1;",
      "uniform uvec4 uCon2;",
      "uniform uvec4 uCon3;",
      "in vec2 vUV;",
      "out vec4 frag;",
      "#define A_GPU 1",
      "#define A_GLSL 1",
      "#define FSR_EASU_F 1",
      FFX_DEFINES,
      FFX_EASU_BLOCK,
      "AF4 FsrEasuRF(AF2 p){ return AF4(texture(uTex, p + uTexel * vec2(-0.5,  0.5)).r, texture(uTex, p + uTexel * vec2( 0.5,  0.5)).r, texture(uTex, p + uTexel * vec2( 0.5, -0.5)).r, texture(uTex, p + uTexel * vec2(-0.5, -0.5)).r); }",
      "AF4 FsrEasuGF(AF2 p){ return AF4(texture(uTex, p + uTexel * vec2(-0.5,  0.5)).g, texture(uTex, p + uTexel * vec2( 0.5,  0.5)).g, texture(uTex, p + uTexel * vec2( 0.5, -0.5)).g, texture(uTex, p + uTexel * vec2(-0.5, -0.5)).g); }",
      "AF4 FsrEasuBF(AF2 p){ return AF4(texture(uTex, p + uTexel * vec2(-0.5,  0.5)).b, texture(uTex, p + uTexel * vec2( 0.5,  0.5)).b, texture(uTex, p + uTexel * vec2( 0.5, -0.5)).b, texture(uTex, p + uTexel * vec2(-0.5, -0.5)).b); }",
      "void main(){",
      "  AF3 c;",
      "  FsrEasuF(c, AU2(gl_FragCoord.xy), uCon0, uCon1, uCon2, uCon3);",
      "  frag = vec4(c, 1.0);",
      "}"
    ].join("\n");
  }

  function rcasFrag() {
    return [
      "#version 300 es",
      "precision highp float;",
    "out vec4 frag;",
      "uniform sampler2D uTex;",
      "uniform uvec4 uCon;",
      "in vec2 vUV;",
      "out vec4 frag;",
      "#define A_GPU 1",
      "#define A_GLSL 1",
      "#define FSR_RCAS_F 1",
      FFX_DEFINES,
      FFX_RCAS_BLOCK,
      "AF4 FsrRcasLoadF(ASU2 p){ return texelFetch(uTex, p, 0); }",
      "void main(){",
      "  AF1 r, g, b;",
      "  FsrRcasF(r, g, b, AU2(gl_FragCoord.xy), uCon);",
      "  frag = vec4(r, g, b, 1.0);",
      "}"
    ].join("\n");
  }

  function compile(type, source) {
    var shader = gl.createShader(type);
    gl.shaderSource(shader, source);
    gl.compileShader(shader);
    if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
      console.error("[XCG upscaler] shader error:", gl.getShaderInfoLog(shader));
      return null;
    }
    return shader;
  }

  function link(fragSource) {
    var program = gl.createProgram();
    var vs = compile(gl.VERTEX_SHADER, VERT);
    var fs = compile(gl.FRAGMENT_SHADER, fragSource);
    if (!vs || !fs) return null;
    gl.attachShader(program, vs);
    gl.attachShader(program, fs);
    gl.bindAttribLocation(program, 0, "aPos");
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      console.error("[XCG upscaler] link error:", gl.getProgramInfoLog(program));
      return null;
    }
    return program;
  }

  function f2u4(gl, location, values) {
    var bits = new Uint32Array(new Float32Array(values).buffer);
    gl.uniform4ui(location, bits[0], bits[1], bits[2], bits[3]);
  }

  var quadBuffer = null;
  function bindQuad() {
    if (!quadBuffer) {
      quadBuffer = gl.createBuffer();
      gl.bindBuffer(gl.ARRAY_BUFFER, quadBuffer);
      gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    }
    gl.bindBuffer(gl.ARRAY_BUFFER, quadBuffer);
    gl.enableVertexAttribArray(0);
    gl.vertexAttribPointer(0, 2, gl.FLOAT, false, 0, 0);
  }

  function videoTexture(video) {
    if (!videoTexture.tex) videoTexture.tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, videoTexture.tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
    try {
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, video);
    } catch (e) {
      return false;
    }
    return video.videoWidth > 0;
  }
  var videoTexRef = videoTexture;

  function ensureFbo(width, height) {
    if (fbo && fboSize[0] === width && fboSize[1] === height) return true;
    if (fboTex) gl.deleteTexture(fboTex);
    if (fbo) gl.deleteFramebuffer(fbo);
    fboTex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, fboTex);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, null);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    fbo = gl.createFramebuffer();
    gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);
    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, fboTex, 0);
    var complete = gl.checkFramebufferStatus(gl.FRAMEBUFFER) === gl.FRAMEBUFFER_COMPLETE;
    gl.bindFramebuffer(gl.FRAMEBUFFER, null);
    fboSize = [width, height];
    return complete;
  }

  function start() {
    if (mode !== "fsr1" || canvas || rafId) return;
    video = document.querySelector("video");
    if (!video || video.videoWidth === 0) return;

    canvas = document.createElement("canvas");
    canvas.className = video.className + " xcg-upscale-canvas";
    canvas.style.cssText = window.getComputedStyle(video).cssText;
    canvas.style.visibility = "visible";
    canvas.style.opacity = "1";
    video.parentElement.insertBefore(canvas, video);
    video.style.visibility = "hidden";

    gl = canvas.getContext("webgl2", { alpha: false, antialias: false, powerPreference: "high-performance", preserveDrawingBuffer: false });
    if (!gl) { console.error("[XCG upscaler] WebGL2 unavailable"); teardown(); return; }

    progEasu = link(easuFrag());
    progRcas = link(rcasFrag());
    if (!progEasu || !progRcas) { console.error("[XCG upscaler] shader compile failed"); teardown(); return; }
    uniformEasu = {
      tex: gl.getUniformLocation(progEasu, "uTex"),
      texel: gl.getUniformLocation(progEasu, "uTexel"),
      c0: gl.getUniformLocation(progEasu, "uCon0"),
      c1: gl.getUniformLocation(progEasu, "uCon1"),
      c2: gl.getUniformLocation(progEasu, "uCon2"),
      c3: gl.getUniformLocation(progEasu, "uCon3")
    };
    uniformRcas = { tex: gl.getUniformLocation(progRcas, "uTex"), con: gl.getUniformLocation(progRcas, "uCon") };

    resize();

    detachObserver = new MutationObserver(function () {
      if (mode === "fsr1" && canvas && !canvas.isConnected) attachToStream();
    });
    detachObserver.observe(document.documentElement, { childList: true, subtree: true });

    var loop = function () {
      if (mode !== "fsr1" || !canvas) { rafId = 0; return; }
      if (!document.hidden && video && !video.paused && !video.ended) render();
      if (video && typeof video.requestVideoFrameCallback === "function") rafId = video.requestVideoFrameCallback(loop);
      else rafId = requestAnimationFrame(loop);
    };
    if (typeof video.requestVideoFrameCallback === "function") rafId = video.requestVideoFrameCallback(loop);
    else rafId = requestAnimationFrame(loop);
  }

  function resize() {
    if (!canvas || !gl) return;
    var dpr = window.devicePixelRatio || 1;
    var rect = canvas.getBoundingClientRect();
    var w = Math.max(2, Math.round(rect.width * dpr));
    var h = Math.max(2, Math.round(rect.height * dpr));
    var cap = Math.min(1, 2560 / w, 1440 / h);
    w = Math.max(2, Math.round(w * cap));
    h = Math.max(2, Math.round(h * cap));
    if (canvas.width !== w || canvas.height !== h) {
      canvas.width = w;
      canvas.height = h;
    }
  }

  function render() {
    if (!video || video.readyState < 2) return;
    resize();
    var dpr = window.devicePixelRatio || 1;
    var rect = canvas.getBoundingClientRect();
    var outW = Math.max(2, Math.round(rect.width * dpr));
    var outH = Math.max(2, Math.round(rect.height * dpr));
    var cap = Math.min(1, 2560 / outW, 1440 / outH);
    outW = Math.max(2, Math.round(outW * cap));
    outH = Math.max(2, Math.round(outH * cap));
    var inW = video.videoWidth, inH = video.videoHeight;

    if (!videoTexture(video)) return;

    // Pass 1: EASU upscale into the FBO.
    if (!ensureFbo(outW, outH)) return;
    gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);
    gl.viewport(0, 0, outW, outH);
    gl.useProgram(progEasu);
    bindQuad();
    gl.activeTexture(gl.TEXTURE0);
    gl.bindTexture(gl.TEXTURE_2D, videoTexture.tex);
    gl.uniform1i(uniformEasu.tex, 0);
    gl.uniform2f(uniformEasu.texel, 1 / inW, 1 / inH);
    f2u4(gl, uniformEasu.c0, [inW / outW, inH / outH, 0.5 * inW / outW - 0.5, 0.5 * inH / outH - 0.5]);
    f2u4(gl, uniformEasu.c1, [1 / inW, 1 / inH, 1 / inW, -1 / inH]);
    f2u4(gl, uniformEasu.c2, [-1 / inW, 2 / inH, 1 / inW, 2 / inH]);
    f2u4(gl, uniformEasu.c3, [0, 4 / inH, 0, 0]);
    gl.drawArrays(gl.TRIANGLES, 0, 3);

    // Pass 2: RCAS sharpen into the canvas.
    gl.bindFramebuffer(gl.FRAMEBUFFER, null);
    gl.viewport(0, 0, outW, outH);
    gl.useProgram(progRcas);
    bindQuad();
    gl.activeTexture(gl.TEXTURE0);
    gl.bindTexture(gl.TEXTURE_2D, fboTex);
    gl.uniform1i(uniformRcas.tex, 0);
    f2u4(gl, uniformRcas.con, [Math.pow(2, -0.4), 0, 0, 0]);
    gl.drawArrays(gl.TRIANGLES, 0, 3);
  }

  function attachToStream() {
    if (mode !== "fsr1") return;
    teardown(false);
    start();
  }

  function teardown(clearCanvasOnly) {
    if (rafId) { if (video && typeof video.cancelVideoFrameCallback === "function") video.cancelVideoFrameCallback(rafId); else cancelAnimationFrame(rafId); rafId = 0; }
    if (detachObserver) { detachObserver.disconnect(); detachObserver = null; }
    if (video) video.style.visibility = "";
    if (canvas) { canvas.remove(); canvas = null; }
    gl = null;
    progEasu = null;
    progRcas = null;
    fbo = null;
    fboTex = null;
  }

  function apply() {
    if (mode === "fsr1") {
      start();
      if (!canvas) {
        // Stream may not be running yet; retry shortly.
        setTimeout(start, 1500);
        setTimeout(start, 4000);
      }
    } else {
      teardown();
    }
  }

  window.addEventListener("message", function (event) {
    var data = event.data;
    if (data && data.type === "xcg-upscaler") {
      mode = data.mode === "fsr1" ? "fsr1" : "off";
      try { localStorage.setItem("XCG.Upscaler", mode); } catch (e) {}
      apply();
    }
  });

  try { mode = localStorage.getItem("XCG.Upscaler") || "off"; } catch (e) {}
  apply();
  setInterval(function () {
    if (mode === "fsr1" && !canvas) {
      video = null;
      start();
    }
  }, 3000);
})();
